### ISSUE TITLE
Add auto complete key

### ISSUE THREAD

**Issue by armink** [p-/eclipse-keybindings#1]
Can you add auto complete key (Alt+/) for atom? I think it is very useful key. Thanks.

**Comment by p-** [comment]
Thanks for your Request.
Do you know an Atom command which matches the eclipse behaviour?

**Comment by armink** [comment]
![qq 20150528222209](https://cloud.githubusercontent.com/assets/1734686/7862389/23eb384e-0588-11e5-84ca-0f492538a86a.png)
I change the autocomplete-plus command. It works OK.
